version: "3.8"

services:
  tequill-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tequill-container
    environment:
      - DISPLAY=:1
      - QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt6/plugins/platforms
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: unless-stopped
