version: "3.8"

services:
  tequill-app:
    image: boykowealth/tequill:latest
    container_name: tequill-container
    ports:
      - "8080:8080"
    environment:
      - DISPLAY=:1
      - QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt6/plugins/platforms
    restart: unless-stopped
